version: "3.7"
services:
  spark-master:
    image: 5200710/spark:spark-master-2.4.5
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - "START_SSH_SERVICE=true"
  spark-worker:
    image: 5200710/spark:spark-worker-2.4.5
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=128m
      - SPARK_EXECUTOR_MEMORY=256m
